--CREATE UNIQUE INDEX NOME ON TABELA(COLUNA(CHAVE)ASC);

DROP TABLE PF;
DROP TABLE PJ;
DROP TABLE FONE;
DROP TABLE ITEM_PRODUTO;
DROP TABLE PEDIDO;
DROP TABLE CLIENTE;
DROP TABLE VENDEDOR;
DROP TABLE CAPACIDADE_ESTOQUE;
DROP TABLE ESTOQUE;
DROP TABLE PRODUTO;
DROP TABLE PRATELEIRA;


CREATE TABLE CLIENTE
(
CODIGO        NUMBER,
NOME          VARCHAR2(60) NOT NULL,
RUA           VARCHAR2(60) NOT NULL,
NR            NUMBER(4) NOT NULL,
BAIRRO        VARCHAR2(50) NOT NULL,
COMPLEMENTO   VARCHAR2(100),
CIDADE        VARCHAR2(50) NOT NULL,
UF            VARCHAR2(2) NOT NULL,
CEP           VARCHAR2(10)
);

ALTER TABLE CLIENTE
ADD CONSTRAINT PK_CLIENTE PRIMARY KEY (CODIGO);

CREATE TABLE PF
(
CODIGO_CLI        NUMBER,
CNPF              VARCHAR2(14) NOT NULL,
RG                VARCHAR2(10) NOT NULL,
DATA_NASCIMENTO   DATE
);

ALTER TABLE PF
ADD CONSTRAINT PK_CLIENTE_PF PRIMARY KEY (CODIGO_CLI);

ALTER TABLE PF
ADD CONSTRAINT FK_PF_CLIENTE FOREIGN KEY (CODIGO_CLI) REFERENCES CLIENTE (CODIGO);

CREATE UNIQUE INDEX IND_CNPF_PF ON PF (CNPF DESC);

CREATE TABLE PJ
(
CODIGO_CLI      NUMBER,
CNPJ            VARCHAR2(19) NOT NULL,
IE              VARCHAR2(10) NOT NULL,
NOME_FANTASIA   VARCHAR2(60) NOT NULL
);

ALTER TABLE PJ
ADD CONSTRAINT PK_CLIENTE_PJ PRIMARY KEY (CODIGO_CLI);

ALTER TABLE PJ
ADD CONSTRAINT FK_PJ_CLIENTE FOREIGN KEY (CODIGO_CLI) REFERENCES CLIENTE (CODIGO);

CREATE UNIQUE INDEX IND_CNPJ_PJ ON PJ (CNPJ DESC);

CREATE TABLE VENDEDOR
(
MATRICULA   NUMBER,
NOME        VARCHAR2(60) NOT NULL,
CNPF        VARCHAR2(14)
);

ALTER TABLE VENDEDOR
ADD CONSTRAINT PK_VENDEDOR PRIMARY KEY (MATRICULA);

CREATE TABLE FONE
(
CODIGO_CLI      NUMBER,
MATRICULA_VEN   NUMBER,
NUMERO          VARCHAR2(14)
);

ALTER TABLE FONE
ADD CONSTRAINT CK_FONE CHECK (
  (CODIGO_CLI IS NULL AND MATRICULA_VEN IS NOT NULL) OR
  (CODIGO_CLI IS NOT NULL AND MATRICULA_VEN IS NULL)
);

ALTER TABLE FONE
ADD CONSTRAINT PK_FONE PRIMARY KEY (NUMERO);  --RESOLVER

ALTER TABLE FONE
ADD CONSTRAINT FK_FONE_CLIENTE FOREIGN KEY (CODIGO_CLI) REFERENCES CLIENTE (CODIGO);

ALTER TABLE FONE
ADD CONSTRAINT FK_FONE_VENDEDOR FOREIGN KEY (MATRICULA_VEN) REFERENCES VENDEDOR (MATRICULA);

CREATE TABLE PRODUTO
(
CODIGO        NUMBER,
DESCRICAO     VARCHAR2(80) NOT NULL,
UNID_MEDIDA   VARCHAR2(10) NOT NULL
);

ALTER TABLE PRODUTO
ADD CONSTRAINT PK_PRODUTO PRIMARY KEY (CODIGO);

CREATE TABLE PRATELEIRA
( 
CODIGO          NUMBER(3),
DESCRICAO       VARCHAR2(50) NOT NULL,
NUMERO_SECOES   NUMBER(2)
);

ALTER TABLE PRATELEIRA
ADD CONSTRAINT PK_PRATELEIRA PRIMARY KEY (CODIGO);

CREATE TABLE PEDIDO
(
NUMERO          NUMBER(6),
DATA            DATE NOT NULL,
PRAZO_ENTREGA   DATE,
RUA             VARCHAR2(80),
NR              NUMBER(4),
BAIRRO          VARCHAR2(50),
COMPLEMENTO     VARCHAR2(100),
CIDADE          VARCHAR2(50),
UF              VARCHAR2(2),
CEP             VARCHAR2(10),
TOTAL_FATURA    NUMBER(8,2),
CODIGO_CLI      NUMBER NOT NULL,
MATRICULA_VEN   NUMBER NOT NULL
);

ALTER TABLE PEDIDO
ADD CONSTRAINT PK_PEDIDO PRIMARY KEY (NUMERO);

ALTER TABLE PEDIDO
ADD CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (CODIGO_CLI) REFERENCES CLIENTE (CODIGO);

ALTER TABLE PEDIDO
ADD CONSTRAINT FK_PEDIDO_VENDEDOR FOREIGN KEY (MATRICULA_VEN) REFERENCES VENDEDOR (MATRICULA);

ALTER TABLE PEDIDO
ADD CONSTRAINT CK_NUMERO_PEDIDO CHECK (NUMERO > 0 AND NUMERO < 100000);

CREATE TABLE ITEM_PRODUTO
(
CODIGO_PRO      NUMBER,
NUMERO_PED      NUMBER(6),
QUANTIDADE      NUMBER(5) NOT NULL,
PRECO_UNITARIO  NUMBER(5,2) NOT NULL,
VALOR_ITEM      NUMBER(7,2)
);

ALTER TABLE ITEM_PRODUTO
ADD CONSTRAINT PK_ITEM_PRODUTO PRIMARY KEY (CODIGO_PRO, NUMERO_PED);

ALTER TABLE ITEM_PRODUTO
ADD CONSTRAINT FK_IP_PRODUTO FOREIGN KEY (CODIGO_PRO) REFERENCES PRODUTO (CODIGO);

ALTER TABLE ITEM_PRODUTO
ADD CONSTRAINT FK_IP_PEDIDO FOREIGN KEY (NUMERO_PED) REFERENCES PEDIDO (NUMERO);

DROP SEQUENCE SEQ_ITEM_ID;
CREATE SEQUENCE SEQ_ITEM_ID INCREMENT BY 2;

COMMENT ON TABLE ITEM_PRODUTO IS 'NAO SEI';
COMMENT ON COLUMN TEM_PRODUTO.CODIGO_PRO IS 'COLUNA QUE FAZ REFERENCIA AO PRODUTO';

CREATE TABLE CAPACIDADE_ESTOQUE
(
CODIGO_PRO  NUMBER,
CODIGO_PRA  NUMBER(3),
QUANTIDADE  NUMBER(5) NOT NULL
);

ALTER TABLE CAPACIDADE_ESTOQUE
ADD CONSTRAINT PK_CAPACIDADE_ESTOQUE PRIMARY KEY (CODIGO_PRO, CODIGO_PRA);

ALTER TABLE CAPACIDADE_ESTOQUE
ADD CONSTRAINT FK_CE_PRODUTO FOREIGN KEY (CODIGO_PRO) REFERENCES PRODUTO (CODIGO);

ALTER TABLE CAPACIDADE_ESTOQUE
ADD CONSTRAINT FK_CE_PRATELEIRA FOREIGN KEY (CODIGO_PRA) REFERENCES PRATELEIRA (CODIGO);

CREATE TABLE ESTOQUE
(
DATA_ENTRADA    DATE,
CODIGO_PRO      NUMBER,
CODIGO_PRA      NUMBER(3),
QUANTIDADE      NUMBER(5) NOT NULL,
DATA_VALIDADE   DATE
);

ALTER TABLE ESTOQUE
ADD CONSTRAINT PK_ESTOQUE PRIMARY KEY (DATA_ENTRADA, CODIGO_PRO, CODIGO_PRA);

ALTER TABLE ESTOQUE
ADD CONSTRAINT FK_ESTOQUE_PRODUTO FOREIGN KEY (CODIGO_PRO) REFERENCES PRODUTO (CODIGO);

ALTER TABLE ESTOQUE
ADD CONSTRAINT FK_ESTOQUE_PRATELEIRA FOREIGN KEY (CODIGO_PRA) REFERENCES PRATELEIRA (CODIGO);

--INSERT INTO TABELA
--SELECT NUMERO AS NUMERO,
--       SEILA AS SEILA 
--FROM DEMO.TABELA
--WHERE (CONDICOES);

--UPDATE TABELA
--SET (O QUE ELE PEDE)
--WHERE (CONDICOES)
--WHERE NUMERO_PED IN (SELECT NUMERO FROM PEDIDO WHERE ...)

--DELETAR PRIMEIRO REGISTROS DAS TABELAS DEPENDENTES DA PRINCIPAL
--DELETE FROM TABELA
--WHERE (CONDICOES)
--CONDICOES INTERNAS DA DEPENDENTE SÃO AS DA PRINCIPAL

--CREATE OR REPLACE VIEW NOME AS
--SELECT ATRIBUTOS DE UMA TABELA E DA PRINCIPA
--FROM TABELA JOIN TABELA PRINCIPAL
--UNION
--SELECT ATRIBUTOS DE OUTRA TABELA E DA PRINCIPAL
--FROM OUTRA TABELA JOIN TABELA PRINCIPAL

SELECT  C.NOME AS CLIENTE,
        P.NUMERO AS PEDIDO,
        P.DATA,
        P.TOTAL_FATURA AS TOTAL
FROM CLIENTE C
INNER JOIN PEDIDO P ON C.CODIGO = P.CODIGO_CLI
WHERE P.TOTAL_FATURA > 2000
ORDER BY C.NOME ASC;




